# Generated by Django 3.2.7 on 2021-09-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khoj',
            old_name='user',
            new_name='user_id',
        ),
    ]
